name: Sync main with dev

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0

      - name: Merge master branch
        run: git merge --no-edit origin/master

      - name: Push changes to dev branch
        uses: ad-m/github-push-action@master
        with:
          branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
